services:
  db:
    image: postgres:16-alpine # Pakai image dari registry (tidak build)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5449:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistent storage

volumes:
  pgdata: # Declare named volume
