/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as AppAnalyticIndexRouteImport } from './routes/_app/analytic/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppProspectIndexRouteImport } from './routes/_app/prospect/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/auth/forgot-password/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as DemoIdIndexRouteImport } from './routes/demo/$id/index'
import { Route as AppProspectIdIndexRouteImport } from './routes/_app/prospect/$id/index'
import { Route as AuthCallbackGoogleIndexRouteImport } from './routes/auth/callback/google/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticIndexRoute = AppAnalyticIndexRouteImport.update({
  id: '/analytic/',
  path: '/analytic/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectIndexRoute = AppProspectIndexRouteImport.update({
  id: '/prospect/',
  path: '/prospect/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/auth/forgot-password/',
  path: '/auth/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIdIndexRoute = DemoIdIndexRouteImport.update({
  id: '/demo/$id/',
  path: '/demo/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProspectIdIndexRoute = AppProspectIdIndexRouteImport.update({
  id: '/prospect/$id/',
  path: '/prospect/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackGoogleIndexRoute = AuthCallbackGoogleIndexRouteImport.update({
  id: '/auth/callback/google/',
  path: '/auth/callback/google/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/': typeof DemoIndexRoute
  '/analytic/': typeof AppAnalyticIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/prospect/': typeof AppProspectIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/demo/$id/': typeof DemoIdIndexRoute
  '/prospect/$id/': typeof AppProspectIdIndexRoute
  '/auth/callback/google/': typeof AuthCallbackGoogleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoIndexRoute
  '/analytic': typeof AppAnalyticIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/prospect': typeof AppProspectIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/demo/$id': typeof DemoIdIndexRoute
  '/prospect/$id': typeof AppProspectIdIndexRoute
  '/auth/callback/google': typeof AuthCallbackGoogleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demo/': typeof DemoIndexRoute
  '/_app/analytic/': typeof AppAnalyticIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/prospect/': typeof AppProspectIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/demo/$id/': typeof DemoIdIndexRoute
  '/_app/prospect/$id/': typeof AppProspectIdIndexRoute
  '/auth/callback/google/': typeof AuthCallbackGoogleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/'
    | '/analytic/'
    | '/dashboard/'
    | '/prospect/'
    | '/settings/'
    | '/auth/forgot-password/'
    | '/auth/reset-password/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/demo/$id/'
    | '/prospect/$id/'
    | '/auth/callback/google/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/analytic'
    | '/dashboard'
    | '/prospect'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/demo/$id'
    | '/prospect/$id'
    | '/auth/callback/google'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo/'
    | '/_app/analytic/'
    | '/_app/dashboard/'
    | '/_app/prospect/'
    | '/_app/settings/'
    | '/auth/forgot-password/'
    | '/auth/reset-password/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/demo/$id/'
    | '/_app/prospect/$id/'
    | '/auth/callback/google/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoIndexRoute: typeof DemoIndexRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  DemoIdIndexRoute: typeof DemoIdIndexRoute
  AuthCallbackGoogleIndexRoute: typeof AuthCallbackGoogleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytic/': {
      id: '/_app/analytic/'
      path: '/analytic'
      fullPath: '/analytic/'
      preLoaderRoute: typeof AppAnalyticIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospect/': {
      id: '/_app/prospect/'
      path: '/prospect'
      fullPath: '/prospect/'
      preLoaderRoute: typeof AppProspectIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$id/': {
      id: '/demo/$id/'
      path: '/demo/$id'
      fullPath: '/demo/$id/'
      preLoaderRoute: typeof DemoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/prospect/$id/': {
      id: '/_app/prospect/$id/'
      path: '/prospect/$id'
      fullPath: '/prospect/$id/'
      preLoaderRoute: typeof AppProspectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback/google/': {
      id: '/auth/callback/google/'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google/'
      preLoaderRoute: typeof AuthCallbackGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticIndexRoute: typeof AppAnalyticIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppProspectIndexRoute: typeof AppProspectIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppProspectIdIndexRoute: typeof AppProspectIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticIndexRoute: AppAnalyticIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppProspectIndexRoute: AppProspectIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppProspectIdIndexRoute: AppProspectIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoIndexRoute: DemoIndexRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  DemoIdIndexRoute: DemoIdIndexRoute,
  AuthCallbackGoogleIndexRoute: AuthCallbackGoogleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
