import { Card, IconBox, SectionHeader } from "@mycustom/ui";
import { NotebookPen, Send, Sparkles } from "lucide-react";
import { useState } from "react";
import toast from "react-hot-toast";
import {
	helperClassName,
	primaryButtonClassName,
	softButtonClassName,
} from "#/components/form-styles";
import { Loader } from "#/components/loader";
import {
	type Prospect,
	toLocalIsoDate,
	useGenerateDraft,
} from "#/modules/prospect";
import { useCreateActivity } from "../hooks/use-create-activity";
import { ActivityFields, type ActivityFieldValues } from "./activity-fields";

export const ActivityLogForm = ({ prospect }: { prospect: Prospect }) => {
	const [values, setValues] = useState<ActivityFieldValues>(() => ({
		channel: prospect.channel ?? "EMAIL",
		outcome: "sent",
		activityDate: toLocalIsoDate(new Date()),
		messageText: "",
	}));
	const createActivity = useCreateActivity(prospect.id);
	const generateDraft = useGenerateDraft(prospect.id);
	const hasNotes = Boolean(prospect.notes?.trim());

	function handleGenerateDraft() {
		generateDraft.mutate(undefined, {
			onSuccess: (draft) =>
				setValues((current) => ({ ...current, messageText: draft })),
			onError: (err) => toast.error(err.message),
		});
	}

	function handleSubmit(event: React.SubmitEvent) {
		event.preventDefault();

		createActivity.mutate(
			{
				channel: values.channel,
				outcome: values.outcome,
				activityDate: values.activityDate,
				messageText: values.messageText.trim() || undefined,
			},
			{
				onSuccess: () => {
					toast.success("Activity logged");
					setValues((current) => ({ ...current, messageText: "" }));
				},
				onError: (err) => toast.error(err.message),
			},
		);
	}

	return (
		<Card className="flex flex-col gap-3.5">
			<SectionHeader
				title="Log activity"
				icon={
					<IconBox tone="mint">
						<NotebookPen className="size-[15px]" />
					</IconBox>
				}
			/>

			<form onSubmit={handleSubmit} className="flex flex-col gap-3">
				<ActivityFields
					idPrefix="activity-log"
					values={values}
					onChange={setValues}
				/>

				<div>
					<button
						type="button"
						onClick={handleGenerateDraft}
						disabled={generateDraft.isPending}
						className={softButtonClassName}
					>
						{generateDraft.isPending ? (
							<Loader />
						) : (
							<Sparkles className="size-3.5" />
						)}
						{generateDraft.isPending ? "Drafting..." : "Draft with AI"}
					</button>
					{!hasNotes && (
						<p className="mt-1.5 rounded-2xl bg-sand-50 px-4.5 py-3.5 text-[13px] leading-relaxed text-sand-700">
							This prospect has no notes yet — the draft will be short and
							generic. Click <strong>Edit</strong> above to add one for a more
							personalized message.
						</p>
					)}
					<p className={helperClassName}>
						Drafts are generated by a third-party AI from the prospect's name,
						company, and notes — don't put sensitive data in notes.
					</p>
				</div>

				<button
					type="submit"
					disabled={createActivity.isPending}
					className={primaryButtonClassName}
				>
					{createActivity.isPending ? <Loader /> : <Send className="size-4" />}
					Save activity
				</button>
			</form>
		</Card>
	);
};
